---
- name: Compare JARs without downloading from JFrog
  hosts: localhost
  gather_facts: no
  vars:
    unix_jar_path: "/path/to/unix/jar/sample.jar"  # Path to JAR on Unix server
    jfrog_api_url: "https://jfrog.example.com/artifactory/api/storage/path/to/sample.jar"  # JFrog API URL
    jfrog_username: "your_username"  # JFrog username
    jfrog_password: "your_password"  # JFrog password
    jfrog_file_list: "/tmp/jfrog_jar_file_list.txt"  # Temp file to store JFrog file list
    unix_file_list: "/tmp/unix_jar_file_list.txt"  # Temp file to store Unix JAR file list
    diff_report: "/tmp/jar_diff_report.txt"  # Path to save the diff report
    email_recipient: "recipient@example.com"  # Email recipient
    email_subject: "JAR Diff Report Without Download"  # Email subject
  tasks:
    - name: Fetch file list from JFrog
      uri:
        url: "{{ jfrog_api_url }}"
        method: GET
        user: "{{ jfrog_username }}"
        password: "{{ jfrog_password }}"
        headers:
          Accept: application/json
      register: jfrog_response

    - name: Parse JFrog response and save file list
      copy:
        content: |
          {% for item in jfrog_response.json.children %}
          {{ item.uri }}
          {% endfor %}
        dest: "{{ jfrog_file_list }}"

    - name: Extract file list from Unix JAR
      shell: |
        unzip -l "{{ unix_jar_path }}" | awk '{print $NF}' | tail -n +4 | head -n -2 > "{{ unix_file_list }}"

    - name: Compare file lists and generate diff report
      shell: |
        diff "{{ unix_file_list }}" "{{ jfrog_file_list }}" > "{{ diff_report }}"
      register: diff_result
      failed_when: diff_result.rc not in [0, 1]

    - name: Check if the diff report is empty
      debug:
        msg: "No differences found between the JAR files."
      when: diff_result.rc == 0

    - name: Send email with diff report
      mail:
        host: "smtp.example.com"  # Replace with your SMTP server
        port: 25
        to: "{{ email_recipient }}"
        subject: "{{ email_subject }}"
        body: |
          Hi,

          Please find the attached diff report for the JAR comparison without downloading from JFrog.

          Regards,
          Automation Team
        attach:
          - "{{ diff_report }}"
      when: diff_result.rc != 0
