---
- name: Compare JAR contents and email the report
  hosts: localhost
  vars:
    jar1_path: "/path/to/first.jar"
    jar2_path: "/path/to/second.jar"
    python_script: "/path/to/compare_jars.py"
    smtp_server: "smtp.example.com"
    smtp_port: 587
    sender_email: "your_email@example.com"
    sender_password: "your_password"
    recipient_email: "recipient@example.com"
  tasks:
    - name: Compare JARs using Python script
      command: >
        python3 {{ python_script }} {{ jar1_path }} {{ jar2_path }}
      register: comparison_result
      failed_when: comparison_result.rc != 0

    - name: Send email with the comparison report
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ sender_email }}"
        password: "{{ sender_password }}"
        to: "{{ recipient_email }}"
        subject: "JAR Content Comparison Report"
        body: |
          Hi,

          Below is the detailed comparison of the JAR contents:

          {{ comparison_result.stdout }}

          Regards,
          Automation Team
      delegate_to: localhost
