---
- name: Execute Python script with parameters
  hosts: localhost
  vars:
    shell_script_path: "/path/to/your/script.py"  # Modify with actual script path
    para1: "value1"  # Modify with the actual parameter value
    para2: "value2"  # Modify with the actual parameter value
  
  tasks:
    - name: Run Python script with parameters
      command: >
        python3 {{ shell_script_path }} {{ para1 }} {{ para2 }}
      register: result

    - name: Show command output
      debug:
        msg: "{{ result.stdout }}"
