---
- name: Compare JARs without writing any files
  hosts: localhost
  gather_facts: no
  vars:
    unix_jar_path: "/path/to/unix/jar/sample.jar"  # Path to JAR on Unix server
    jfrog_api_url: "https://jfrog.example.com/artifactory/api/storage/path/to/sample.jar"  # JFrog API URL
    jfrog_username: "your_username"  # JFrog username
    jfrog_password: "your_password"  # JFrog password
    email_recipient: "recipient@example.com"  # Email recipient
    email_subject: "JAR Diff Report Without Files"  # Email subject
  tasks:
    - name: Fetch file list from JFrog
      uri:
        url: "{{ jfrog_api_url }}"
        method: GET
        user: "{{ jfrog_username }}"
        password: "{{ jfrog_password }}"
        headers:
          Accept: application/json
      register: jfrog_response

    - name: Parse JFrog file list
      set_fact:
        jfrog_file_list: >-
          {{ jfrog_response.json.children | map(attribute='uri') | map('trim') | list }}

    - name: Extract file list from Unix JAR
      shell: |
        unzip -l "{{ unix_jar_path }}" | awk '{print $NF}' | tail -n +4 | head -n -2
      register: unix_file_list_raw

    - name: Parse Unix JAR file list
      set_fact:
        unix_file_list: "{{ unix_file_list_raw.stdout_lines | map('trim') | list }}"

    - name: Compare file lists in memory
      set_fact:
        diff_output: >-
          Differences Found:
          {{ (unix_file_list | difference(jfrog_file_list)) | join('\n') }}
          {{ (jfrog_file_list | difference(unix_file_list)) | join('\n') }}

    - name: Send email with diff output
      mail:
        host: "smtp.example.com"  # Replace with your SMTP server
        port: 25
        to: "{{ email_recipient }}"
        subject: "{{ email_subject }}"
        body: |
          Hi,

          Below are the differences found during the JAR comparison:

          {{ diff_output }}

          Regards,
          Automation Team
      when: diff_output | length > 0

    - name: Print message if no differences are found
      debug:
        msg: "No differences found between the JAR files."
      when: diff_output is not defined or diff_output | length == 0
