---
- name: Compare file contents in JARs entirely in memory
  hosts: localhost
  gather_facts: no
  vars:
    unix_jar_path: "/path/to/unix/jar/sample.jar"  # Path to Unix JAR
    jfrog_api_base_url: "https://jfrog.example.com/artifactory/api/storage/path/to/jar"  # Base URL for JFrog JAR
    jfrog_username: "your_username"  # JFrog username
    jfrog_password: "your_password"  # JFrog password
    email_recipient: "recipient@example.com"  # Email recipient
    email_subject: "Detailed JAR Comparison Report"  # Email subject
  tasks:
    - name: List files in Unix JAR
      shell: |
        unzip -l "{{ unix_jar_path }}" | awk '{print $NF}' | tail -n +4 | head -n -2
      register: unix_file_list_raw

    - name: Parse Unix JAR file list
      set_fact:
        unix_file_list: "{{ unix_file_list_raw.stdout_lines | map('trim') | list }}"

    - name: Compare file contents between Unix JAR and JFrog
      set_fact:
        diff_report: ""

    - name: Process each file
      loop: "{{ unix_file_list }}"
      loop_control:
        label: "{{ item }}"
      tasks:
        - name: Read file content from Unix JAR
          shell: |
            unzip -p "{{ unix_jar_path }}" "{{ item }}"
          register: unix_file_content
          ignore_errors: yes

        - name: Fetch corresponding file from JFrog
          uri:
            url: "{{ jfrog_api_base_url }}/{{ item }}"
            method: GET
            user: "{{ jfrog_username }}"
            password: "{{ jfrog_password }}"
          register: jfrog_file_response
          ignore_errors: yes

        - name: Compare file contents in memory
          set_fact:
            diff_result: >-
              {% if unix_file_content.stdout | default('') != (jfrog_file_response.content | b64decode | default('')) %}
              File: {{ item }} has differences.
              Unix JAR content:
              {{ unix_file_content.stdout }}

              JFrog content:
              {{ jfrog_file_response.content | b64decode }}
              {% else %}
              File: {{ item }} has no differences.
              {% endif %}

        - name: Append diff result to report
          set_fact:
            diff_report: >-
              {{ diff_report }}
              {{ diff_result }}

    - name: Send email with diff report
      mail:
        host: "smtp.example.com"  # Replace with your SMTP server
        port: 25
        to: "{{ email_recipient }}"
        subject: "{{ email_subject }}"
        body: |
          Hi,

          Below is the detailed comparison of JAR file contents:

          {{ diff_report }}

          Regards,
          Automation Team
