---
- name: Run Python script inline without temporary file
  hosts: target_server
  become: yes
  vars:
    path_of_the_shell_script: "/path/to/your/shell_script.sh"
    environment: ""
    type_of_command: ""

  tasks:
    - name: Execute inline Python script with parameters
      ansible.builtin.shell: |
        python3 - << 'EOF'
        import subprocess
        import sys

        def run_shell_script(shell_script_path, env=None, command_type=None):
            try:
                command = ['/bin/bash', shell_script_path]
                if env:
                    command += ['-E', env]
                if command_type:
                    command += ['-c', command_type]

                subprocess.run(command, check=True)
                print("Shell script executed successfully.")
            except subprocess.CalledProcessError as e:
                print(f"Error executing shell script: {e}")

        if __name__ == "__main__":
            shell_script_path = "{{ path_of_the_shell_script }}"
            env = "{{ environment }}"
            command_type = "{{ type_of_command }}"
            run_shell_script(shell_script_path, env or None, command_type or None)
        EOF
